name: deploy
on:
  push:
    branches:
      - 'master'
jobs:
  lint:
    runs-on: ubuntu-latest
    run: npm run lint  
  test:
    runs-on: ubuntu-latest
    run: npm run tests  
  build:
    runs-on: ubuntu-latest
    run: npm run build  